spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

hash:
  batch-size: 1000
  thread-pool:
    size: 4
    queue-capacity: 1000

hash-cache:
  capacity: 10000
  refill-threshold-percent: 20
  refill-batch-size: 3000
  wait-timeout: 200ms

hash-cache-executor:
  pool-size: 2
  queue-capacity: 10

server:
  port: 8080
  servlet:
    context-path: /api/v1

app:
  shortener:
    base-url: http://localhost:8080/api/v1
  url-cache:
    ttl: 30d
    version: v1
    module: urlshortener
    urlEntity: url
  cleaner:
    cron: "0 0 3 * * *"     # every day at 03:00
    retention: 365d

logging:
  level:
    root: info