spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: password
      timeout: 1000ms
      client-type: lettuce
      default-ttl-seconds: 3600
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: info

shortener:
  address: http://localhost:8080/

hash:
  storage:
    size: 100000
    update_percentage: 10
  cache:
    size: 100000
    update_percentage: 10

executor:
  hash:
    core-pool-size: 5
    max-pool-size: 15
    thread-name-prefix: 'HashExecutor-'

scheduler:
  expired-urls-clean:
    cron: "0 * * * * *"
    zone: "Europe/Moscow"
    batch-size: 10000
    fetch-limit: 10000
    batch-delay-ms: 50
    executor-config:
      core-pool-size: 5
      max-pool-size: 15
      thread-name-prefix: 'ExpiredCleaner-'
