CREATE SEQUENCE IF NOT EXISTS unique_number_seq
    START WITH 14776336
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 50
    NO CYCLE;


CREATE TABLE IF NOT EXISTS hash (
    hash VARCHAR(32) PRIMARY KEY
);