CREATE SEQUENCE IF NOT EXISTS unique_number_seq
    START WITH 14776336
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1000;

CREATE TABLE IF NOT EXISTS hash
(
    hash VARCHAR(6) PRIMARY KEY
    );

CREATE TABLE IF NOT EXISTS url
(
    hash       VARCHAR(6) PRIMARY KEY,
    url        VARCHAR(256) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
    );