CREATE SEQUENCE IF NOT EXISTS unique_number_seq
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS url (
    hash VARCHAR(6) NOT NULL PRIMARY KEY,
    url VARCHAR(256) NOT NULL,
    created_at TIMESTAMP DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS hash (
    hash VARCHAR(6) NOT NULL PRIMARY KEY
);